Update README.md
paynl/prestashop16-plugin pull request #14
Opened 2020-08-14 12:15 UTC by bryantvandenberg

2020-08-17 13:28 UTC, woutse requested changes

2020-08-17 13:28 UTC, woutse commented on README.md
> +<h1 align="center">PAY. PrestaShop plugin/h1>
de html is hier niet goed

2020-08-19 13:46 UTC, annevelden requested changes

2020-08-19 13:46 UTC, annevelden commented on README.md
> +2. 2. Go to *Modules and Services* > *Modules and Services*
Hier staat een 2 te veel.

2020-08-19 13:46 UTC, annevelden commented on README.md
> +**More information on this plugin can be found on https://docs.pay.nl/**
Een directe link naar de prestashop docs is handiger hier

2020-08-20 08:14 UTC, woutse commented on README.md
> +**More information on this plugin can be found on hhttps://docs.pay.nl/plugins#prestashop**
niet goed.

2020-08-20 08:15 UTC, woutse requested changes
zie comments

2020-08-20 09:24 UTC, annevelden commented on README.md
> +1. log into the Prestashop admin
Elke andere PrestaShop is geschreven met hoofdletter P en S.
Alles gelijk aan elkaar maken en dan is het helemaal toppie

2020-08-20 09:24 UTC, annevelden requested changes
Zie comment

2020-08-20 09:30 UTC, annevelden approved these changes

2020-08-20 09:49 UTC, merged