feature/PLUG-335
paynl/prestashop16-plugin pull request #18
Opened 2021-04-15 13:53 UTC by annevelden

changed notificaton to include denied

2021-04-20 13:55 UTC, kevinverschoor commented on paynl_paymentmethods/controllers/front/notification.php
> +        $message = $this->module->l('The order could not be made with this paymentmethod due to either the order amount being to high or to low or the payment being denied') . '.</br>';
Deze regel staat niet in de vertalingen? :)

Weet niet of het nodig is of niet maar ja het viel me gewoon op dat er geen nederlandse tekst voor is terwijl er wel een vertalings bestand is.

2021-05-03 13:26 UTC, kevinverschoor approved these changes

2021-05-11 15:47 UTC, woutse requested changes
See comments

2021-06-02 11:29 UTC, kevinverschoor approved these changes

2021-06-07 15:35 UTC, woutse approved these changes

2021-06-07 15:35 UTC, merged